In [2]:
pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (3.9.1)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\david\pycharmprojects\musqlwebscrapp\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [13]:
import requests
from bs4 import BeautifulSoup
import mysql.connector
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [14]:
def connect_to_database():
    return mysql.connector.connect(
        host="khushiconfecciones.com",
        database="u506324710_deportivo",
        user="u506324710_Daviddeportivo",
        password="Tamedotothepa1$"
    )

In [15]:
def run_query(query):
    db = connect_to_database()  # Conecta a la base de datos
    cursor = db.cursor()        # Crea un cursor para ejecutar comandos SQL
    cursor.execute(query)       # Ejecuta la consulta SQL proporcionada
    result = cursor.fetchall()  # Recupera todos los resultados de la consulta
    cursor.close()              # Cierra el cursor
    db.close()                  # Cierra la conexi√≥n a la base de datos
    return pd.DataFrame(result) # Convierte los resultados en un DataFrame de Pandas
    print(db)

In [16]:
query1 = """
SELECT * FROM Partidos
"""

In [17]:
df1 = run_query(query1)

In [18]:
df1

          0           1     2   3    4    5    6    7        8           9
0     25246  2023-07-14  None   2  3.0  1.0   20   13  Hdhdjdj        None
1     25247  2023-07-14  None   2  1.0  2.0   16   14     None        None
2     25248  2023-07-15  None   2  2.0  2.0    2   12     None        None
3     25249  2023-07-15  None   2  0.0  0.0   10    6     None        None
4     25250  2023-07-16  None   2  0.0  1.0    3    4     None        None
...     ...         ...   ...  ..  ...  ...  ...  ...      ...         ...
7500  35674  2024-05-26  None  24  0.0  3.0  155  150     None  2024-07-23
7501  35675  2024-05-26  None  24  1.0  2.0  154  160     None  2024-07-23
7502  35676  2024-05-26  None  24  2.0  2.0  168  162     None  2024-07-23
7503  35677  2024-05-26  None  24  1.0  0.0  165  161     None  2024-07-23
7504  35678  2024-05-26  None  24  1.0  1.0  149  152     None  2024-07-23

[7505 rows x 10 columns]